baseURL = "https://www.andreaono.com"
languageCode = "en-us"
title = "Andrea Onos Portfolio"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "Andrea Ono"
  description = "Andrea Ono Portfolio"
  hideAutoMenu = false
  
  # Pagination options
  paginate = 3
  multipage = true

  # Dark mode
  darkMode = true

[[menu.main]]
  name = "External"
  url = "https://www.andreaono.com"

[social]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
