baseURL = "https://www.andreaono.com"
languageCode = "en-us"
title = "Andrea Ono | Animation and Illustration"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "Andrea Ono"
  description = "Andrea Ono | Animation and Illustration"
  hideAutoMenu = false
  
  # Pagination options
  paginate = 3
  multipage = false

  # Dark mode
  darkMode = false

[[menu.main]]
  name = "About"
  url = "/about"
